#!/usr/bin/env python3
"""file_playwright_failure_issue.py
Purpose:   Phase 2 automation (#465) — convert Playwright E2E failures into
           durable, dedup'd GitHub Issues via file_hygiene_issue.py. Mirrors
           file_codex_review_findings.py (Phase 1 for Codex reviews); sibling
           filer in the same lane.

           Closes the gap that PR #461 and PR #469 surfaced: when Playwright
           fails on a PR, the failure signal lives only in a transient PR
           comment that evaporates when the PR closes. No persistent Issue,
           no dedup, no way to see "this test has been flaky for 3 weeks."
           After this script wires into playwright-regression.yml, every
           unique failure becomes an Issue with a stable signature — so the
           same flake dedups to one Issue across PRs, and can be classified
           once and remembered forever via `auto:suppressed`.

Called by: .github/workflows/playwright-regression.yml (inline step after
           the parse_playwright_results.py step). Runs when either the main
           suite or the education suite had a non-zero exit, OR when the
           whole job was cancelled (timeout at the runner level).

Trust:     Internal CI path. Reads local artifact files only; no parsing of
           user-controlled comments. The Playwright JSON reporter output is
           generated by our own workflow, not user input.

Env vars:
  Required (from workflow):
    GITHUB_TOKEN / GH_TOKEN           auth (auto in Actions)
    GITHUB_REPOSITORY                 owner/repo (auto in Actions)
    REPO                              owner/repo (workflow-supplied mirror)
    RUN_URL                           full URL of this workflow run
  Input files (defaults — override if workflow changes filenames):
    PW_OUTPUT_FILE                    playwright-output.txt (main suite)
    EDU_OUTPUT_FILE                   education-output.txt (education suite)
  Suite exit codes (optional — used to detect cancellation vs test fail):
    PW_EXIT                           main suite exit code
    EDU_EXIT                          education suite exit code
  Kill switches (both default to opt-in-required):
    AUTOMATION_ENABLED                master — 'false' short-circuits
    PLAYWRIGHT_FILER_ENABLED          this filer — defaults FALSE (opt-in)
  Forwarded to file_hygiene_issue.py subprocess:
    AUTOMATION_MAX_DAILY_ISSUES       integer cap (default 5 on helper side)
    STATUS_ISSUE_NUMBER               pinned filer-status Issue (optional)

Behavior:
  1. Gate on AUTOMATION_ENABLED AND PLAYWRIGHT_FILER_ENABLED. Silent exit
     on either false. Filer defaults OFF — LT flips the var after canary.
  2. Parse PW_OUTPUT_FILE and EDU_OUTPUT_FILE into Playwright JSON-reporter
     structures. Tolerate missing files and unparseable output.
  3. If a suite emitted no JSON and its exit code looks cancelled (rc 124
     or 143 on timeout), or if neither file exists but RUN_URL is set,
     file ONE `suite-level` Issue rather than guessing per-test failures.
  4. Otherwise, walk the JSON for `status != 'expected'` results, extract
     (file, test_name, category), and build per-test findings.
  5. Categorize each failure: `timeout` (error message contains test-timeout
     phrasing), `infra` (page load / network / browser errors), else
     `assertion` (default).
  6. Route labels: `area:education` if file path starts with tbm/education-*,
     else `area:qa`. All get `auto:filed`, `kind:bug`, `severity:major`.
  7. Compute identity dict — stable across runs: {check, test_file, test_name,
     category}. Pipe each finding JSON to file_hygiene_issue.py subprocess.
  8. Structured JSON-line logging to stdout.

Exit: 0 success (any combination of filed / skipped / rate-limited).
      1 validation error (missing required env, bad worker state).
      2 unexpected error (subprocess failure propagating up).
"""

import hashlib
import json
import os
import re
import subprocess
import sys


CHECK_ID = 'playwright-failure'
CHECK_TITLE = 'Playwright E2E'
SUITE_CHECK_ID = 'playwright-suite'
SUITE_CHECK_TITLE = 'Playwright E2E Suite'

# Exit codes that indicate runner-level cancellation (timeout, SIGKILL, etc.).
# Distinguishes from per-test failure (usually rc=1 with parseable JSON).
CANCELLED_EXIT_CODES = {124, 137, 143}

TIMEOUT_PATTERNS = (
    'test timeout',
    'timeout of',
    'exceeded timeout',
    'waiting for',  # often times out waiting for selector
)

INFRA_PATTERNS = (
    'net::',
    'ERR_',
    'page.goto',
    'protocol error',
    'browser has been closed',
    'target closed',
    'connection refused',
)


def log(event, **fields):
    """Structured JSON-line logging to stdout (grep-able in workflow logs)."""
    fields['event'] = event
    sys.stdout.write(json.dumps(fields, sort_keys=True) + '\n')
    sys.stdout.flush()


def env_flag(name, default=True):
    raw = os.environ.get(name, '').strip().lower()
    if raw == '':
        return default
    return raw not in ('false', '0', 'no', 'off')


def env_optional(name, default=''):
    return os.environ.get(name, '').strip() or default


def short_hash(text, length=12):
    return hashlib.sha256((text or '').encode('utf-8')).hexdigest()[:length]


def safe_read(path):
    """Return file contents or empty string on missing/unreadable."""
    if not path or not os.path.isfile(path):
        return ''
    try:
        with open(path, 'r', encoding='utf-8', errors='replace') as f:
            return f.read()
    except (OSError, IOError) as exc:
        log('file-read-error', path=path, error=str(exc)[:200])
        return ''


def extract_playwright_json(output_text):
    """Locate and parse the Playwright JSON reporter blob inside stdout.

    Mirrors the parse strategy in parse_playwright_results.py — the JSON
    reporter emits a top-level object with a `stats` key. The surrounding
    stdout may include npm install chatter, progress bars, etc.
    """
    if not output_text:
        return None
    stripped = output_text.strip()
    # Fast path: entire output is a single JSON document.
    if stripped.startswith('{'):
        try:
            data = json.loads(stripped)
            if 'stats' in data:
                return data
        except json.JSONDecodeError:
            pass
    # Look for a fresh JSON object after a newline.
    idx = stripped.find('\n{')
    if idx != -1:
        try:
            data = json.loads(stripped[idx + 1:])
            if 'stats' in data:
                return data
        except json.JSONDecodeError:
            pass
    # Last resort: scan for a single-line JSON blob with stats key.
    for line in output_text.splitlines():
        line = line.strip()
        if line.startswith('{') and '"stats"' in line:
            try:
                data = json.loads(line)
                if 'stats' in data:
                    return data
            except json.JSONDecodeError:
                continue
    return None


def categorize_failure(error_text):
    """Return 'timeout' | 'infra' | 'assertion' based on error message."""
    if not error_text:
        return 'assertion'
    lowered = error_text.lower()
    for pat in TIMEOUT_PATTERNS:
        if pat in lowered:
            return 'timeout'
    for pat in INFRA_PATTERNS:
        if pat in lowered:
            return 'infra'
    return 'assertion'


def derive_area_label(test_file):
    """Education-specific test files route to area:education; else area:qa."""
    if not test_file:
        return 'area:qa'
    lowered = test_file.lower()
    if 'education' in lowered or 'homework' in lowered or 'sparkle' in lowered:
        return 'area:education'
    return 'area:qa'


def walk_failures(report):
    """Yield (test_file, test_name, error_message) for each failed test."""
    if not report or not isinstance(report, dict):
        return
    # Playwright JSON reporter: suites[].specs[].tests[].results[].
    # A spec is failed if any of its tests have an 'unexpected' status result.
    for suite in report.get('suites') or []:
        yield from _walk_suite(suite, '')


def _walk_suite(suite, path_prefix):
    file_path = suite.get('file') or path_prefix
    for spec in suite.get('specs') or []:
        title = spec.get('title') or '(untitled)'
        for test in spec.get('tests') or []:
            status = (test.get('status') or '').lower()
            # Playwright marks failing tests 'unexpected'. We also catch
            # 'flaky' so known-flakes surface in the dedup log.
            if status not in ('unexpected', 'flaky'):
                continue
            # Collect error messages across result attempts; the last one is
            # usually the most informative (final retry's failure).
            msgs = []
            for result in test.get('results') or []:
                err = result.get('error') or {}
                if err.get('message'):
                    msgs.append(err.get('message'))
                for e in result.get('errors') or []:
                    if e.get('message'):
                        msgs.append(e.get('message'))
            error_text = ' | '.join(msgs)[:2000]
            yield (file_path, title, error_text)
    # Recurse into nested suites (describe blocks).
    for nested in suite.get('suites') or []:
        yield from _walk_suite(nested, file_path)


def build_per_test_finding(pr_number, test_file, test_name, error_text, run_url):
    """Build the finding dict piped into file_hygiene_issue.py for one test."""
    category = categorize_failure(error_text)
    identity = {
        'check': CHECK_ID,
        'test_file': (test_file or '').strip(),
        'test_name': (test_name or '').strip(),
        'category': category,
    }
    area = derive_area_label(test_file)
    extra_labels = ['auto:filed', 'kind:bug', 'severity:major', area,
                    'type:ui']
    title = 'Playwright {0}: {1}'.format(category, test_name or '(unnamed test)')
    # Body: keep concise, link the run for drill-down.
    evidence_lines = [
        '**Test file:** `{0}`'.format(test_file or '(unknown)'),
        '**Test name:** {0}'.format(test_name or '(unnamed)'),
        '**Failure category:** {0}'.format(category),
        '**Latest run:** {0}'.format(run_url or '(no run URL set)'),
    ]
    if error_text:
        snippet = error_text[:1200].replace('\r', '')
        evidence_lines.append('\n**Error (first 1200 chars):**')
        evidence_lines.append('```\n{0}\n```'.format(snippet))
    details = (
        'Filed automatically by the Playwright failure router (#465). '
        'If this failure is flaky and not a real regression, apply the '
        '`auto:suppressed` label to permanently dismiss. If it is a real '
        'regression, investigate and fix — the Issue will auto-close when '
        'the next Playwright run passes this test (#463-style Phase 2 '
        'auto-close is pending for Playwright).'
    )
    return {
        'check': CHECK_ID,
        'check_title': CHECK_TITLE,
        'title': title,
        'identity': identity,
        'evidence': {'details': '\n'.join(evidence_lines)},
        'details': details,
        'extra_labels': extra_labels,
    }


def build_suite_finding(reason, run_url, pw_exit, edu_exit):
    """Build the finding dict for a suite-level cancellation or infra failure."""
    identity = {
        'check': SUITE_CHECK_ID,
        'reason': reason,
    }
    extra_labels = ['auto:filed', 'kind:bug', 'severity:major', 'area:infra']
    title = 'Playwright suite {0}'.format(reason)
    evidence_lines = [
        '**Suite-level failure reason:** {0}'.format(reason),
        '**Main suite exit:** {0}'.format(pw_exit if pw_exit is not None else '(unknown)'),
        '**Education suite exit:** {0}'.format(edu_exit if edu_exit is not None else '(unknown)'),
        '**Latest run:** {0}'.format(run_url or '(no run URL set)'),
        '',
        'A per-test breakdown was not available (no parseable Playwright '
        'JSON, or the runner timed out at the job level). Drill into the '
        'workflow run to inspect artifacts.',
    ]
    details = (
        'Filed by the Playwright failure router (#465) when per-test '
        'parsing was not possible. Typical causes: job-level timeout '
        '(30-min runner cap), network blip reaching thompsonfams.com, or '
        'Playwright install failure. Apply `auto:suppressed` once the '
        'root cause is remediated to prevent reopen churn.'
    )
    return {
        'check': SUITE_CHECK_ID,
        'check_title': SUITE_CHECK_TITLE,
        'title': title,
        'identity': identity,
        'evidence': {'details': '\n'.join(evidence_lines)},
        'details': details,
        'extra_labels': extra_labels,
    }


def call_hygiene_filer(finding):
    """Pipe finding JSON to file_hygiene_issue.py. Return (ok, rc)."""
    here = os.path.dirname(os.path.abspath(__file__))
    target = os.path.join(here, 'file_hygiene_issue.py')
    if not os.path.isfile(target):
        log('filer-missing', path=target)
        return (False, -1)
    payload = json.dumps(finding)
    proc = subprocess.run(
        ['python3', target],
        input=payload,
        text=True,
        capture_output=True,
    )
    if proc.returncode != 0:
        log('filer-error',
            rc=proc.returncode,
            stderr=(proc.stderr or '').strip()[:800])
        return (False, proc.returncode)
    log('filer-ok', stdout=(proc.stdout or '').strip()[:400])
    return (True, 0)


def parse_exit_code(name):
    raw = os.environ.get(name, '').strip()
    if not raw:
        return None
    try:
        return int(raw)
    except ValueError:
        return None


def main():
    # 1. Kill switches.
    if not env_flag('AUTOMATION_ENABLED', True):
        log('skip', reason='AUTOMATION_ENABLED=false')
        return 0
    # Opt-in by default — LT flips PLAYWRIGHT_FILER_ENABLED=true after canary.
    if not env_flag('PLAYWRIGHT_FILER_ENABLED', False):
        log('skip', reason='PLAYWRIGHT_FILER_ENABLED=false (opt-in required)')
        return 0

    run_url = env_optional('RUN_URL')
    pw_file = env_optional('PW_OUTPUT_FILE', 'playwright-output.txt')
    edu_file = env_optional('EDU_OUTPUT_FILE', 'education-output.txt')
    pw_exit = parse_exit_code('PW_EXIT')
    edu_exit = parse_exit_code('EDU_EXIT')

    # 2. Read + parse both suite outputs.
    pw_text = safe_read(pw_file)
    edu_text = safe_read(edu_file)
    pw_report = extract_playwright_json(pw_text)
    edu_report = extract_playwright_json(edu_text)

    log('parse-summary',
        pw_file_found=bool(pw_text),
        pw_parsed=bool(pw_report),
        pw_exit=pw_exit,
        edu_file_found=bool(edu_text),
        edu_parsed=bool(edu_report),
        edu_exit=edu_exit)

    # 3. Detect suite-level cancellation — no parseable JSON + cancelled rc.
    suite_cancelled = False
    cancel_reason_parts = []
    if not pw_report and pw_exit in CANCELLED_EXIT_CODES:
        suite_cancelled = True
        cancel_reason_parts.append('main-suite-rc-{0}'.format(pw_exit))
    if not edu_report and edu_exit in CANCELLED_EXIT_CODES:
        suite_cancelled = True
        cancel_reason_parts.append('education-suite-rc-{0}'.format(edu_exit))
    # Also treat "both files empty but some exit was non-zero" as suite-level.
    if (not pw_report and not edu_report
            and ((pw_exit or 0) > 0 or (edu_exit or 0) > 0)
            and not cancel_reason_parts):
        suite_cancelled = True
        cancel_reason_parts.append('unparseable-output')

    if suite_cancelled:
        reason = ','.join(cancel_reason_parts) or 'cancelled'
        finding = build_suite_finding(reason, run_url, pw_exit, edu_exit)
        ok, rc = call_hygiene_filer(finding)
        log('suite-filed', ok=ok, rc=rc, reason=reason)
        # Return 0 even on partial failure — we logged; don't block workflow.
        return 0

    # 4-5. Walk per-test failures from whichever suites parsed.
    per_test_findings = []
    seen_sigs = set()
    for report in (pw_report, edu_report):
        if not report:
            continue
        for test_file, test_name, error_text in walk_failures(report):
            sig_key = (test_file or '', test_name or '',
                       categorize_failure(error_text))
            if sig_key in seen_sigs:
                continue
            seen_sigs.add(sig_key)
            per_test_findings.append(
                (test_file, test_name, error_text)
            )

    log('failures-found', count=len(per_test_findings))
    if not per_test_findings:
        log('no-op', reason='no-failures-detected')
        return 0

    # 6-7. File each unique failure.
    pr_number = env_optional('PR_NUMBER')  # best-effort; not required
    filed = 0
    errored = 0
    for test_file, test_name, error_text in per_test_findings:
        finding = build_per_test_finding(
            pr_number, test_file, test_name, error_text, run_url
        )
        ok, rc = call_hygiene_filer(finding)
        if ok:
            filed += 1
        else:
            errored += 1
    log('done', filed=filed, errored=errored, total=len(per_test_findings))
    return 0


if __name__ == '__main__':
    sys.exit(main())
